POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET http://localhost:5080/api/copy_rates_from_pos?symbol=DJI30&timeframe=H1&count=2

